<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\hospital.application\hospital.application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Pages\Auth\" />
    <Folder Include="Components\Pages\Doctor\" />
  </ItemGroup>

</Project>
